apiVersion: v1

kind: Service

metadata:

  name: api-service
  labels:
    app: api-service

spec:
  ports:
  - port: 8081
    name: http

  selector:
    app: api-service
  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-service-deployment-v1

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: api-service

  template: # template for the pods
    metadata:
      labels:
        app: api-service

    spec:
      containers:
      - name: api-service
        image: saurabh2204/online-appointment-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087