zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    doctor-service: /vet/**
    visits-service: /visit/**
    patient-service: /customer/**
    api-gateway: /gateway/**
logging.level.org.springframework: DEBUG

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

spring:
  profiles: default
  application:
     name: api-gateway  # Service registers under this name
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
      