spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: doctor-service
          uri: http://doctor-service:8888
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service:9999
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: patient-service
          uri: http://patient-service:8080
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2